package chatstore

import (
	"bytes"
	"io"
)

// ReverseScanner scans a file backwards, line by line.
type ReverseScanner struct {
	f        io.ReadSeeker
	buf      []byte
	pos      int64
	err      error
	line     []byte // partial line being built (suffix). nil initially.
	chunk    []byte // current buffer window
	curr     []byte // last scanned line
	finished bool
}

// NewReverseScanner creates a new scanner that reads backwards starting from the end of the file.
func NewReverseScanner(f io.ReadSeeker, bufferSize int64) (*ReverseScanner, error) {
	end, err := f.Seek(0, io.SeekEnd)
	if err != nil {
		return nil, err
	}
	// Cap buffer size to file size to avoid unnecessary allocation for small files
	if end < bufferSize {
		bufferSize = end
	}
	// Avoid 0 buffer size
	if bufferSize < 1 {
		bufferSize = 1 // minimal buffer
	}

	return &ReverseScanner{
		f:   f,
		buf: make([]byte, bufferSize),
		pos: end,
	}, nil
}

// Scan advances the scanner to the next line (moving backwards).
// It returns false when scanning stops, either by reaching the start of the file or an error.
func (s *ReverseScanner) Scan() bool {
	if s.finished || s.err != nil {
		return false
	}

	for {
		// If current chunk is exhausted, read more
		if len(s.chunk) == 0 {
			if s.pos == 0 {
				// Reached start of file
				if s.line != nil {
					// Return the accumulated line (even if empty, as it represents the first line)
					s.curr = s.line
					s.line = nil
					s.finished = true
					return true
				}
				// No more lines
				s.finished = true
				return false
			}

			// Read next chunk
			readSize := int64(len(s.buf))
			if s.pos < readSize {
				readSize = s.pos
			}
			s.pos -= readSize

			if _, err := s.f.Seek(s.pos, io.SeekStart); err != nil {
				s.err = err
				return false
			}

			// We use only the beginning of buf for the read data
			n, err := io.ReadFull(s.f, s.buf[:readSize])
			if err != nil {
				s.err = err
				return false
			}
			s.chunk = s.buf[:n]
		}

		// Find the last newline in the current chunk
		lastIdx := bytes.LastIndexByte(s.chunk, '\n')
		if lastIdx >= 0 {
			// Found a newline.
			// The line consists of the part after newline in chunk + any previously accumulated suffix.
			part := s.chunk[lastIdx+1:]

			// Construct the full line
			fullLine := make([]byte, len(part)+len(s.line))
			copy(fullLine, part)
			copy(fullLine[len(part):], s.line)

			s.curr = fullLine
			s.line = []byte{} // Mark that we are scanning a new line (which is structurally previous)

			// Update chunk to exclude the processed part and the newline
			s.chunk = s.chunk[:lastIdx]
			return true
		}

		// No newline found in chunk.
		// Prepend chunk to s.line (effectively appending s.line to s.chunk)
		newLine := make([]byte, len(s.chunk)+len(s.line))
		copy(newLine, s.chunk)
		copy(newLine[len(s.chunk):], s.line)
		s.line = newLine
		s.chunk = nil // Chunk exhausted
	}
}

// Bytes returns the most recent line generated by a call to Scan.
// The underlying array may point to data that will be overwritten by a subsequent call to Scan.
// (Actually in our implementation we allocate new slices, but the interface implies caution).
func (s *ReverseScanner) Bytes() []byte {
	return s.curr
}

// Text returns the most recent line generated by a call to Scan as a string.
func (s *ReverseScanner) Text() string {
	return string(s.curr)
}

// Err returns the first non-EOF error that was encountered by the Scanner.
func (s *ReverseScanner) Err() error {
	if s.err == io.EOF {
		return nil
	}
	return s.err
}
